title: George Aalbers
logo: https://stress-in-action.nl/wp-content/uploads/2023/06/George-Aalbers.jpg
description: Stress-in-Action // AmsterdamUMC
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
